### ISSUE TITLE
Please update for macOS Catalina

### ISSUE THREAD

**Issue by stonexing** [faizauthar12/ASUS_A411UF_Hackintosh#1]

**Comment by faizauthar12** [comment]
i had been switched to windows due to unworking HDMI, perhaps i will continue this configuration after i get ssd

**Comment by stonexing** [comment]
I have got almost everything work for my S4000VA with 411 motherboard
Maybe you can try my EFI

**Comment by faizauthar12** [comment]
done ;) 3129a8b074cac96908553fa62616b30902cabd43
